[[chain]]
id = "testnet"
key_format = { type = "bech32", account_key_prefix = "cosmospub", consensus_key_prefix = "cosmosvalconspub" }
[[validator]]
chain_id = "testnet"
# The address of the tendemint node
addr = "tcp://0.0.0.0:26658"
reconnect = true # true is the default
secret_key = "/root/home/assets/tmkms/kms-identity.key"
protocol_version = "v0.34"
[[providers.softsign]]
chain_ids = ["testnet"]
key_type = "consensus"
path = "/root/home/assets/tmkms/signing.key"